### ISSUE TITLE
index_path - no such file or directory exists

### ISSUE THREAD

**Issue by richard-dinh** [learningequality/ricecooker#311]
* ricecooker version: most recent develop branch
* Python version: 3.7.9
* Operating System: Windows

### Description

Line with issue: [(https://github.com/learningequality/ricecooker/blob/develop/ricecooker/utils/downloader.py#L818)](https://github.com/learningequality/ricecooker/blob/develop/ricecooker/utils/downloader.py#L818)
When running the [Sciensation](https://github.com/learningequality/sushi-chef-sciensation) sushi chef script breaks down when it hits the above line and gives a `Errno 2`.

![error](https://user-images.githubusercontent.com/58611530/109726500-b3018000-7b67-11eb-96bc-e1f15e356e48.PNG)

This line was added in the following [commit](https://github.com/learningequality/ricecooker/commit/ad79ef3150e5beee6379795412abb5bf144de7eb)
### What I Did

```
Run Sciensation Chef
```

**Comment by kollivier** [comment]
@richard-dinh Oops, sorry about that! Fixing it should just be a matter of calling `os.makedirs` on `os.path.dirname(os.path.join(temp_dir, index_path))` with `exist_ok=True` before trying to write the file.

**Comment by richard-dinh** [comment]
@kollivier Thank you for the help! I added that in and noticed that issue, however there is no `index.html` at the root of zip folder. Was this intended? Was this [line](https://github.com/learningequality/ricecooker/commit/ad79ef3150e5beee6379795412abb5bf144de7eb#diff-58863fc4828722eb55772876b30ce481ba87e6c422b15aca36c365372b6c8df9L801) adding `index.html` to the root?

**Comment by richard-dinh** [comment]
Is this [line](https://github.com/learningequality/ricecooker/commit/ad79ef3150e5beee6379795412abb5bf144de7eb#diff-58863fc4828722eb55772876b30ce481ba87e6c422b15aca36c365372b6c8df9R745) meant to be `if self.relative_links`? If so, would we still need to call `os.makedirs` since we do not want to make a directory at the root for `index.html`?

**Comment by kollivier** [comment]
@richard-dinh No, that line should be `if not self.relative_links` as it is now.  When `self.relative_links` is True, we dynamically create a root `index.html` file that simply redirects to the page at `index_path`. That is the `entrypoint` that you noticed earlier.

**Comment by richard-dinh** [comment]
@kollivier  I'm do not see an `index.html` at the root after running the chef and downloading the zipfile. I only see an `index.html` located at `index_path`

**Comment by kollivier** [comment]
@richard-dinh If you are calling `create_predictable_zip` yourself instead of using `export_page_as_zip`, you will need to replicate the logic for specifying the `entrypoint` in the same way that function does it.

**Comment by richard-dinh** [comment]
@kollivier Got it! I was working on the Sciensation Sushi Chef and even when updating the code, it was not displaying on Kolibri correctly. I added `relative_links=False` to `ArchiveDownloader`  and that fixed the problem!

**Comment by kollivier** [comment]
@richard-dinh Glad that got things working for you! If you happen to have more details about what exactly was going wrong, I'd love to have them. The idea was that we would always use `relative_links=True` (and eventually remove the option), so if there are still bugs with it, it would be good to know what those are.

**Comment by richard-dinh** [comment]
@kollivier When I do not set `relative_links=False` the page's assets get `404` errors.  What I'm guessing is that this [line](https://github.com/learningequality/ricecooker/blob/develop/ricecooker/utils/html.py#L78) does not run in `replace_links`, when `relative_links=False` so the links in the root `index.html` are not relative to the file

**Comment by kollivier** [comment]
@richard-dinh When `relative_links=True`, the root `index.html` should just redirect to the actual page in the archive, wherever it is. That is, the entire page contents of the root `index.html` should just be this HTML snippet:

https://github.com/learningequality/ricecooker/blob/b346a9983df7a0f2b25922ce30021491c4f162c1/ricecooker/utils/zip.py#L5

Where `url` is the zip-relative path to `index_path` in the archive. If your root `index.html` has the actual page content in it, then maybe you are overwriting the root `index.html` that was created by calling `create_predictable_zip` with an entrypoint? Note that the point of implementing `relative_links=True` is to stop us from having to rewrite all the links in `index.html` to make them relative to the zip root by just redirecting to the actual page instead of copying the content to the root `index.html`. Sorry, I know `relative_links` as a term doesn't exactly make this clear.

Probably the reason this is causing problem is because the chef was written to address issues that are fixed by moving to using the entrypoint system, and those 'fixes' are now actually unnecessary and breaking things.

**Comment by richard-dinh** [comment]
@kollivier I believe for the Sciensation Chef, I was overwriting some content of `index.html` at the root. I overwrote the content before calling `create_predicatable_zip`. I did not pass in an entrypoint for `create_predictable_zip` but rather the zip directory created by `create_zip_dir_for_page`

**Comment by kollivier** [comment]
@richard-dinh Okay, moving forward, the way to do that would be to create the zip dir and edit the `index_path` HTML file in that zip dir, instead of the root `index.html` file. Then you create the entrypoint to redirect to the edited file.

**Comment by richard-dinh** [comment]
@kollivier Got it! I'll make sure to do that going forward

**Comment by rtibbles** [comment]
Fixed in #322
